#!/usr/bin/env python3
"""
Generate test data using outlet images for outdoor gear
"""

import firebase_admin
from firebase_admin import credentials, firestore
from datetime import datetime, timezone
import os

# Initialize Firebase
cred = credentials.Certificate("serviceAccountKey.json")
firebase_admin.initialize_app(cred)
db = firestore.client()

def generate_outlet_test_data():
    """Generate test data using outlet images"""
    
    # Test data with outlet images
    test_items = [
        # Rock Climbing Gear
        {
            'title': 'Black Diamond Momentum Climbing Harness',
            'description': 'Comfortable and adjustable climbing harness perfect for gym climbing and outdoor sport routes. Features breathable mesh waist belt, 4 gear loops, and adjustable leg loops. UIAA certified for safety.',
            'price': 45.00,
            'originalPrice': 69.95,
            'brand': 'Black Diamond',
            'category': 'Climbing Gear',
            'gender': 'Unisex',
            'size': 'Medium',
            'color': 'Blue',
            'condition': 'Very Good',
            'material': 'Nylon Webbing, Mesh',
            'tags': ['climbing harness', 'gym climbing', 'sport climbing', 'adjustable', 'uiaa certified'],
            'status': 'pending',
            'sellerId': 'test_admin_001',
            'sellerName': 'Vertical Adventures',
            'sellerEmail': 'climb@vertical.com',
            'isTestData': True,
            'images': ['/src/assets/outlet images/rock-climbing-harness.jpg']
        },
        {
            'title': 'Mammut 9.5mm Phoenix Dry Climbing Rope',
            'description': '70m dynamic single rope with Dry treatment technology providing water resistance. Featuring UIAA and CE certified construction with middle mark for safe rappelling. Perfect for sport, trad, and alpine climbing.',
            'price': 125.00,
            'originalPrice': 179.95,
            'brand': 'Mammut',
            'category': 'Climbing Gear',
            'gender': 'Unisex',
            'size': '70m x 9.5mm',
            'color': 'Safety Orange',
            'condition': 'Very Good',
            'material': 'Nylon Core, Polyester Sheath',
            'tags': ['dynamic rope', 'dry treatment', 'single rope', 'middle mark', 'uiaa certified'],
            'status': 'pending',
            'sellerId': 'test_admin_001',
            'sellerName': 'Elite Climbing Gear',
            'sellerEmail': 'elite@climbinggear.com',
            'isTestData': True,
            'images': ['/src/assets/outlet images/climbing-ropes.jpg']
        },
        {
            'title': 'La Sportiva Solution Comp Climbing Shoes',
            'description': 'Aggressive performance climbing shoe with P3 system for precise edging and hooking. Features sticky Vibram XS Grip2 rubber and Fast Lacing System. Perfect for advanced sport climbing and bouldering.',
            'price': 129.00,
            'originalPrice': 189.00,
            'brand': 'La Sportiva',
            'category': 'Climbing Gear',
            'gender': 'Unisex',
            'size': '42',
            'color': 'White/Lily Orange',
            'condition': 'Excellent',
            'material': 'Leather, Vibram XS Grip2',
            'tags': ['aggressive climbing', 'sport climbing', 'bouldering', 'vibram rubber', 'performance'],
            'status': 'pending',
            'sellerId': 'test_admin_001',
            'sellerName': 'Comp Climbing Pro',
            'sellerEmail': 'comp@climbingpro.com',
            'isTestData': True,
            'images': ['/src/assets/outlet images/climbing-shoes.jpg']
        },
        {
            'title': 'Black Diamond Positron Screwgate Carabiners (Set of 6)',
            'description': 'High-strength screwgate carabiners with keylock nose for snag-free clipping. Features 24kN gate-open strength and smooth gate action. Perfect for belaying, rappelling, and anchor building.',
            'price': 35.00,
            'originalPrice': 59.95,
            'brand': 'Black Diamond',
            'category': 'Climbing Gear',
            'gender': 'Unisex',
            'size': 'Standard',
            'color': 'Silver',
            'condition': 'Good',
            'material': 'Aluminum Alloy',
            'tags': ['carabiners', 'screwgate', 'keylock', 'belaying', 'anchors'],
            'status': 'pending',
            'sellerId': 'test_admin_001',
            'sellerName': 'Safety First Climbing',
            'sellerEmail': 'safety@climbing.com',
            'isTestData': True,
            'images': ['/src/assets/outlet images/carabiners.jpg']
        },
        {
            'title': 'Petzl Meteor Climbing Helmet',
            'description': 'Lightweight and comfortable climbing helmet with excellent ventilation. Features adjustable headband and chin strap. UIAA and CE certified for impact protection. Perfect for all types of climbing.',
            'price': 55.00,
            'originalPrice': 89.95,
            'brand': 'Petzl',
            'category': 'Climbing Gear',
            'gender': 'Unisex',
            'size': 'Medium',
            'color': 'Red',
            'condition': 'Very Good',
            'material': 'Polycarbonate Shell, EPS Foam',
            'tags': ['climbing helmet', 'lightweight', 'ventilated', 'uiaa certified', 'impact protection'],
            'status': 'pending',
            'sellerId': 'test_admin_001',
            'sellerName': 'Head Protection Pro',
            'sellerEmail': 'head@protection.com',
            'isTestData': True,
            'images': ['/src/assets/outlet images/climbing-helmet.jpg']
        },
        {
            'title': 'Black Diamond HotForge Quickdraws (Set of 12)',
            'description': 'Lightweight quickdraws with wiregate carabiners for fast clipping. Features 24kN gate-open strength and color-coded dogbones. Perfect for sport climbing and gym use.',
            'price': 85.00,
            'originalPrice': 129.95,
            'brand': 'Black Diamond',
            'category': 'Climbing Gear',
            'gender': 'Unisex',
            'size': '12cm',
            'color': 'Mixed Colors',
            'condition': 'Excellent',
            'material': 'Aluminum, Nylon Webbing',
            'tags': ['quickdraws', 'wiregate', 'sport climbing', 'lightweight', 'color coded'],
            'status': 'pending',
            'sellerId': 'test_admin_001',
            'sellerName': 'Quick Draw Supply',
            'sellerEmail': 'quick@drawsupply.com',
            'isTestData': True,
            'images': ['/src/assets/outlet images/quickdraws.jpg']
        },
        {
            'title': 'Friction Labs Chalk Bag with Belt',
            'description': 'Premium chalk bag with adjustable belt and fleece lining. Features secure closure and comfortable fit. Perfect for bouldering, sport climbing, and gym sessions.',
            'price': 18.00,
            'originalPrice': 29.95,
            'brand': 'Friction Labs',
            'category': 'Climbing Gear',
            'gender': 'Unisex',
            'size': 'Standard',
            'color': 'Black',
            'condition': 'Good',
            'material': 'Nylon, Fleece Lining',
            'tags': ['chalk bag', 'fleece lining', 'adjustable belt', 'bouldering', 'gym climbing'],
            'status': 'pending',
            'sellerId': 'test_admin_001',
            'sellerName': 'Chalk Master',
            'sellerEmail': 'chalk@master.com',
            'isTestData': True,
            'images': ['/src/assets/outlet images/chalk-bag.jpg']
        },
        {
            'title': 'Black Diamond ATC-XP Belay Device',
            'description': 'Versatile belay device with extended plate for smooth rope handling. Features two rope slots for different diameters and textured surface for better grip. Perfect for gym and outdoor climbing.',
            'price': 22.00,
            'originalPrice': 34.95,
            'brand': 'Black Diamond',
            'category': 'Climbing Gear',
            'gender': 'Unisex',
            'size': 'Standard',
            'color': 'Silver',
            'condition': 'Very Good',
            'material': 'Aluminum Alloy',
            'tags': ['belay device', 'atc', 'smooth handling', 'versatile', 'textured surface'],
            'status': 'pending',
            'sellerId': 'test_admin_001',
            'sellerName': 'Belay Device Pro',
            'sellerEmail': 'belay@device.com',
            'isTestData': True,
            'images': ['/src/assets/outlet images/belay-device.jpg']
        },
        {
            'title': 'Friction Labs Premium Chalk (4oz)',
            'description': 'High-quality climbing chalk with optimal moisture absorption. Features fine texture for better grip and long-lasting performance. Perfect for all climbing styles.',
            'price': 12.00,
            'originalPrice': 19.95,
            'brand': 'Friction Labs',
            'category': 'Climbing Gear',
            'gender': 'Unisex',
            'size': '4oz',
            'color': 'White',
            'condition': 'New',
            'material': 'Magnesium Carbonate',
            'tags': ['climbing chalk', 'moisture absorption', 'premium', 'fine texture', 'long lasting'],
            'status': 'pending',
            'sellerId': 'test_admin_001',
            'sellerName': 'Chalk Supply Co',
            'sellerEmail': 'supply@chalk.com',
            'isTestData': True,
            'images': ['/src/assets/outlet images/climbing-chalk.jpg']
        },
        {
            'title': 'Black Diamond C4 Camalot Set (0.3-3)',
            'description': 'Complete set of camming devices for trad climbing. Features dual-axle design for wide range and color-coded sizing. Perfect for placing protection on traditional routes.',
            'price': 245.00,
            'originalPrice': 399.95,
            'brand': 'Black Diamond',
            'category': 'Climbing Gear',
            'gender': 'Unisex',
            'size': '0.3-3',
            'color': 'Mixed Colors',
            'condition': 'Very Good',
            'material': 'Aluminum, Steel Springs',
            'tags': ['cams', 'trad climbing', 'dual axle', 'color coded', 'protection'],
            'status': 'pending',
            'sellerId': 'test_admin_001',
            'sellerName': 'Trad Climbing Gear',
            'sellerEmail': 'trad@climbing.com',
            'isTestData': True,
            'images': ['/src/assets/outlet images/climbing-cams.jpg']
        },
        {
            'title': 'DMM Wallnuts Set (1-11)',
            'description': 'Complete set of passive protection nuts for trad climbing. Features color-coded sizing and durable construction. Perfect for placing protection in cracks and fissures.',
            'price': 65.00,
            'originalPrice': 99.95,
            'brand': 'DMM',
            'category': 'Climbing Gear',
            'gender': 'Unisex',
            'size': '1-11',
            'color': 'Mixed Colors',
            'condition': 'Good',
            'material': 'Aluminum Alloy',
            'tags': ['nuts', 'passive protection', 'trad climbing', 'color coded', 'crack protection'],
            'status': 'pending',
            'sellerId': 'test_admin_001',
            'sellerName': 'Passive Protection Pro',
            'sellerEmail': 'passive@protection.com',
            'isTestData': True,
            'images': ['/src/assets/outlet images/climbing-nuts.jpg']
        },
        {
            'title': 'Osprey Mutant 38L Climbing Pack',
            'description': 'Versatile climbing backpack with rope carry system and gear organization. Features hydration compatibility and durable construction. Perfect for cragging and multi-pitch routes.',
            'price': 95.00,
            'originalPrice': 149.95,
            'brand': 'Osprey',
            'category': 'Climbing Gear',
            'gender': 'Unisex',
            'size': '38L',
            'color': 'Black',
            'condition': 'Very Good',
            'material': 'Nylon, Ripstop',
            'tags': ['climbing pack', 'rope carry', 'gear organization', 'hydration', 'durable'],
            'status': 'pending',
            'sellerId': 'test_admin_001',
            'sellerName': 'Pack Solutions',
            'sellerEmail': 'pack@solutions.com',
            'isTestData': True,
            'images': ['/src/assets/outlet images/climbing-backpack.jpg']
        },
        
        # Skiing Gear
        {
            'title': 'Salomon QST 106 Ski Boots - Men\'s',
            'description': 'Versatile all-mountain ski boots with excellent flex for varied terrain. Features customizable fit with heat-moldable liner and adjustable buckles. Perfect for powder, groomers, and backcountry skiing.',
            'price': 189.00,
            'originalPrice': 299.95,
            'brand': 'Salomon',
            'category': 'Skiing Gear',
            'gender': 'Men',
            'size': '27.5',
            'color': 'Black/Red',
            'condition': 'Very Good',
            'material': 'Polyurethane Shell, Heat-moldable Liner',
            'tags': ['ski boots', 'all mountain', 'heat moldable', 'adjustable', 'versatile'],
            'status': 'pending',
            'sellerId': 'test_admin_001',
            'sellerName': 'Ski Boot Pro',
            'sellerEmail': 'boots@skipro.com',
            'isTestData': True,
            'images': ['/src/assets/outlet images/ski-boots.jpg']
        },
        {
            'title': 'Atomic Bent Chetler 100 Skis (2023)',
            'description': 'Lightweight all-mountain skis with playful feel and excellent float. Features carbon layering for responsiveness and rocker-camber-rocker profile. Perfect for powder and variable conditions.',
            'price': 299.00,
            'originalPrice': 499.95,
            'brand': 'Atomic',
            'category': 'Skiing Gear',
            'gender': 'Unisex',
            'size': '184cm',
            'color': 'Black/White',
            'condition': 'Excellent',
            'material': 'Wood Core, Carbon Fiber',
            'tags': ['skis', 'all mountain', 'lightweight', 'powder', 'carbon fiber'],
            'status': 'pending',
            'sellerId': 'test_admin_001',
            'sellerName': 'Atomic Ski Specialist',
            'sellerEmail': 'atomic@skispecialist.com',
            'isTestData': True,
            'images': ['/src/assets/outlet images/skis.jpg']
        },
        {
            'title': 'Black Diamond Expedition Carbon Ski Poles',
            'description': 'Ultralight carbon fiber ski poles with adjustable length. Features comfortable grips and durable construction. Perfect for backcountry skiing and mountaineering.',
            'price': 45.00,
            'originalPrice': 79.95,
            'brand': 'Black Diamond',
            'category': 'Skiing Gear',
            'gender': 'Unisex',
            'size': 'Adjustable 110-130cm',
            'color': 'Black',
            'condition': 'Very Good',
            'material': 'Carbon Fiber, Aluminum',
            'tags': ['ski poles', 'carbon fiber', 'adjustable', 'ultralight', 'backcountry'],
            'status': 'pending',
            'sellerId': 'test_admin_001',
            'sellerName': 'Pole Master',
            'sellerEmail': 'poles@master.com',
            'isTestData': True,
            'images': ['/src/assets/outlet images/ski-poles.jpg']
        },
        {
            'title': 'POC Obex SPIN Ski Helmet',
            'description': 'Advanced ski helmet with SPIN technology for rotational impact protection. Features adjustable ventilation and comfortable fit. Perfect for all-mountain and freestyle skiing.',
            'price': 75.00,
            'originalPrice': 129.95,
            'brand': 'POC',
            'category': 'Skiing Gear',
            'gender': 'Unisex',
            'size': 'Medium',
            'color': 'White',
            'condition': 'Excellent',
            'material': 'Polycarbonate Shell, EPS Foam',
            'tags': ['ski helmet', 'spin technology', 'rotational protection', 'adjustable ventilation'],
            'status': 'pending',
            'sellerId': 'test_admin_001',
            'sellerName': 'Helmet Safety Pro',
            'sellerEmail': 'helmet@safety.com',
            'isTestData': True,
            'images': ['/src/assets/outlet images/ski-helmet.jpg']
        },
        {
            'title': 'Oakley Flight Deck XM Ski Goggles',
            'description': 'Premium ski goggles with Prizm lens technology for enhanced visibility. Features spherical lens design and comfortable fit. Perfect for all light conditions.',
            'price': 89.00,
            'originalPrice': 149.95,
            'brand': 'Oakley',
            'category': 'Skiing Gear',
            'gender': 'Unisex',
            'size': 'Large',
            'color': 'Black/Red',
            'condition': 'Very Good',
            'material': 'Polycarbonate Lens, O Matter Frame',
            'tags': ['ski goggles', 'prizm lens', 'spherical', 'enhanced visibility', 'all conditions'],
            'status': 'pending',
            'sellerId': 'test_admin_001',
            'sellerName': 'Goggle Vision Pro',
            'sellerEmail': 'goggles@vision.com',
            'isTestData': True,
            'images': ['/src/assets/outlet images/ski-goggles.jpg']
        },
        {
            'title': 'Hestra Army Leather Ski Gloves',
            'description': 'Premium leather ski gloves with excellent warmth and dexterity. Features waterproof membrane and adjustable wrist closure. Perfect for cold weather skiing.',
            'price': 65.00,
            'originalPrice': 109.95,
            'brand': 'Hestra',
            'category': 'Skiing Gear',
            'gender': 'Unisex',
            'size': 'Large',
            'color': 'Brown',
            'condition': 'Good',
            'material': 'Leather, Gore-Tex Membrane',
            'tags': ['ski gloves', 'leather', 'waterproof', 'warm', 'dexterity'],
            'status': 'pending',
            'sellerId': 'test_admin_001',
            'sellerName': 'Glove Master',
            'sellerEmail': 'gloves@master.com',
            'isTestData': True,
            'images': ['/src/assets/outlet images/ski-gloves.jpg']
        },
        {
            'title': 'Arc\'teryx Beta AR Ski Jacket',
            'description': 'Versatile ski jacket with Gore-Tex Pro technology for waterproof protection. Features adjustable hood and multiple pockets. Perfect for backcountry and resort skiing.',
            'price': 199.00,
            'originalPrice': 349.95,
            'brand': 'Arc\'teryx',
            'category': 'Skiing Gear',
            'gender': 'Unisex',
            'size': 'Medium',
            'color': 'Black',
            'condition': 'Very Good',
            'material': 'Gore-Tex Pro, Nylon',
            'tags': ['ski jacket', 'gore tex', 'waterproof', 'versatile', 'backcountry'],
            'status': 'pending',
            'sellerId': 'test_admin_001',
            'sellerName': 'Jacket Pro',
            'sellerEmail': 'jacket@pro.com',
            'isTestData': True,
            'images': ['/src/assets/outlet images/ski-jacket.jpg']
        },
        {
            'title': 'Patagonia Powder Bowl Ski Pants',
            'description': 'Insulated ski pants with waterproof shell and comfortable fit. Features adjustable waist and reinforced knees. Perfect for cold weather and powder skiing.',
            'price': 85.00,
            'originalPrice': 149.95,
            'brand': 'Patagonia',
            'category': 'Skiing Gear',
            'gender': 'Unisex',
            'size': '32x32',
            'color': 'Navy',
            'condition': 'Good',
            'material': 'Waterproof Shell, Insulated',
            'tags': ['ski pants', 'insulated', 'waterproof', 'adjustable', 'powder'],
            'status': 'pending',
            'sellerId': 'test_admin_001',
            'sellerName': 'Pants Pro',
            'sellerEmail': 'pants@pro.com',
            'isTestData': True,
            'images': ['/src/assets/outlet images/ski-pants.jpg']
        }
    ]
    
    created_items = []
    for item_data in test_items:
        # Add common fields
        item_data.update({
            'createdAt': datetime.now(timezone.utc),
            'lastUpdated': datetime.now(timezone.utc),
            'views': 0,
            'isTestData': True
        })
        
        # Add to Firestore
        doc_ref = db.collection('items').add(item_data)
        created_items.append({
            'id': doc_ref[1].id,
            'title': item_data['title'],
            'brand': item_data['brand'],
            'category': item_data['category']
        })
    
    print(f"✅ Successfully generated {len(created_items)} test items using outlet images")
    print(f"📊 Categories: Climbing Gear ({len([i for i in test_items if i['category'] == 'Climbing Gear'])}), Skiing Gear ({len([i for i in test_items if i['category'] == 'Skiing Gear'])})")
    
    return created_items

if __name__ == "__main__":
    generate_outlet_test_data() 